import { AutoUpdateSystems } from "../models/AutoUpdateSystems";
import { Computermodels } from "../models/ComputerModel";
import { Computertypes } from "../models/ComputerTypes";
import { Entities } from "../models/Entities";
import { Groups } from "../models/Groups";
import { Locations } from "../models/Locations";
import { Manufacturers } from "../models/Manufacturers";
import { Networks } from "../models/Networks";
import { States } from "../models/States";
import { Users } from "../models/Users";

export interface ComputerDTO  {
    id: number;
    computertypes?: Computertypes;
    computermodels?: Computermodels;
    entities?: Entities;
    networks?: Networks;
    locations?: Locations;
    autoupdatesystems?: AutoUpdateSystems;
    users?: Users;
    groups?: Groups;
    states?: States;
    manufacturers?: Manufacturers;
    name: string;
    serial?: string;
    otherserial: string;
    contact: string;
    contact_num: string;
    comment?: string;
    date_mod?: string;
    is_template: number;
    template_name?: string;
    is_deleted: number;
    is_dynamic: number;
    ticket_tco?: string;
    uuid: string;
    date_creation?: string;
    is_recursive: number;
    last_inventory_update?: string;
    users_tech?: number;
    groups_tech?: string;
}