import CableForm from "../../components/forms/CableForm";
import CartridgeForm from "../../components/forms/CartridgeForm";
import ComputerForm from "../../components/forms/ComputerForm";
import ConsumableForm from "../../components/forms/ConsumableForm";
import DeviceForm from "../../components/forms/DeviceForm";
import EnclosuresForm from "../../components/forms/EnclosuresForm";
import MonitorForm from "../../components/forms/MonitorForm";
import NetDeviceForm from "../../components/forms/NetworkDeviceForm";
import PassiveDeviceForm from "../../components/forms/PassiveDeviceForm";
import PduForm from "../../components/forms/PduForm";
import PhoneForm from "../../components/forms/PhoneForm";
import PrinterForm from "../../components/forms/PrinterForm";
import RackForm from "../../components/forms/RackForm";
import SimCardForm from "../../components/forms/SimCardForm";
import SoftwareForm from "../../components/forms/SoftwareForm";
import { useGetComputerById } from "../../hooks/Computers/useGetComputerById";
import { useGetMonitorById } from "../../hooks/Monitors/useGetMonitorById";
import { useGetNetworkDeviceById } from "../../hooks/NetworksDevices/useGetNetworkDeviceById";
import { useGetSoftwareById } from "../../hooks/Softwares/useGetSoftwareById";

export interface EditAssetOption {
  name: string;
  useGetAssetData?: () => {
    data: any;
    error: undefined;
    isLoading: boolean;
    get: (id: number) => Promise<void>;
  };
  options: { name: string; content: any }[];
}

export const AssetOptions: EditAssetOption[] = [
  {
    name: "Computers",
    useGetAssetData: useGetComputerById,
    options: [
      { name: "Computers", content: <ComputerForm isEditing={true} /> },
      { name: "Impact Analysis", content: "" },
      { name: "Operating Systems", content: "" },
      { name: "Components", content: "" },
      { name: "Volumes", content: "" },
      { name: "Software", content: "" },
      { name: "Conections", content: "" },
      { name: "Network Ports", content: "" },
      { name: "Sockets", content: "" },
      { name: "Remote Management", content: "" },
      { name: "Management", content: "" },
      { name: "Contracts", content: "" },
      { name: "Documents", content: "" },
      { name: "Virtualization", content: "" },
      { name: "Antiviruses", content: "" },
      { name: "Knowledge Base", content: "" },
      { name: "Tickets", content: "" },
      { name: "Problems", content: "" },
      { name: "Changes", content: "" },
      { name: "Links", content: "" },
      { name: "Certificates", content: "" },
      { name: "Notes", content: "" },
      { name: "Reservations", content: "" },
      { name: "Domains", content: "" },
      { name: "Appliances", content: "" },
      { name: "Database Instances", content: "" },
      { name: "Historical", content: "" },
      { name: "All", content: "" },
    ],
  },
  {
    name: "Monitors",
    useGetAssetData: useGetMonitorById,
    options: [
      { name: "Monitors", content: <MonitorForm isEditing={true} /> },
      { name: "Impact Analysis", content: "" },
      { name: "Operating Systems", content: "" },
      { name: "Software", content: "" },
      { name: "Connections", content: "" },
      { name: "Network Ports", content: "" },
      { name: "Management", content: "" },
      { name: "Contracts", content: "" },
      { name: "Documents", content: "" },
      { name: "Knowledge Base", content: "" },
      { name: "Tickets", content: "" },
      { name: "Problems", content: "" },
      { name: "Changes", content: "" },
      { name: "Links", content: "" },
      { name: "Notes", content: "" },
      { name: "Reservations", content: "" },
      { name: "Domains", content: "" },
      { name: "Appliances", content: "" },
      { name: "Historical", content: "" },
      { name: "All", content: "" },
    ],
  },
  {
    name: "Software",
    useGetAssetData: useGetSoftwareById,
    options: [
      { name: "Software", content: <SoftwareForm isEditing={true} /> },
      { name: "Impact Analysis", content: "" },
      { name: "Versions", content: "" },
      { name: "Licenses", content: "" },
      { name: "Installations", content: "" },
      { name: "Management", content: "" },
      { name: "Contracts", content: "" },
      { name: "Documents", content: "" },
      { name: "Knowledge Base", content: "" },
      { name: "Tickets", content: "" },
      { name: "Problems", content: "" },
      { name: "Changes", content: "" },
      { name: "Links", content: "" },
      { name: "Notes", content: "" },
      { name: "Reservations", content: "" },
      { name: "Domains", content: "" },
      { name: "Appliances", content: "" },
      { name: "Historical", content: "" },
      { name: "All", content: "" },
    ],
  },
  {
    name: "Networkequipments",
    useGetAssetData: useGetNetworkDeviceById,
    options: [
      { name: "Network Devices", content: <NetDeviceForm isEditing={true} /> },
      { name: "Impact Analysis", content: "" },
      { name: "Operating Systems", content: "" },
      { name: "Software", content: "" },
      { name: "Components", content: "" },
      { name: "Volumes", content: "" },
      { name: "Network Ports", content: "" },
      { name: "Network Names", content: "" },
      { name: "Sockets", content: "" },
      { name: "Management", content: "" },
      { name: "Contracts", content: "" },
      { name: "Documents", content: "" },
      { name: "Knowledge Base", content: "" },
      { name: "Tickets", content: "" },
      { name: "Problems", content: "" },
      { name: "Changes", content: "" },
      { name: "Links", content: "" },
      { name: "Notes", content: "" },
      { name: "Reservations", content: "" },
      { name: "Certificates", content: "" },
      { name: "Domains", content: "" },
      { name: "Appliances", content: "" },
      { name: "Historical", content: "" },
      { name: "All", content: "" },
    ],
  },
  {
    name: "Devices",
    useGetAssetData: useGetComputerById,
    options: [
      { name: "Devices", content: <DeviceForm isEditing={true} /> },
      { name: "Impact Analysis", content: "" },
      { name: "Operating Systems", content: "" },
      { name: "Software", content: "" },
      { name: "Components", content: "" },
      { name: "Connections", content: "" },
      { name: "Network Ports", content: "" },
      { name: "Sockets", content: "" },
      { name: "Management", content: "" },
      { name: "Contracts", content: "" },
      { name: "Documents", content: "" },
      { name: "Knowledge Base", content: "" },
      { name: "Tickets", content: "" },
      { name: "Problems", content: "" },
      { name: "Changes", content: "" },
      { name: "Links", content: "" },
      { name: "Notes", content: "" },
      { name: "Reservations", content: "" },
      { name: "Certificates", content: "" },
      { name: "Domains", content: "" },
      { name: "Appliances", content: "" },
      { name: "Historical", content: "" },
      { name: "All", content: "" },
    ],
  },
  {
    name: "Printers",
    useGetAssetData: useGetComputerById,
    options: [
      { name: "Printers", content: <PrinterForm isEditing={true} /> },
      { name: "Impact Analysis", content: "" },
      { name: "Operating Systems", content: "" },
      { name: "Software", content: "" },
      { name: "Cartridges", content: "" },
      { name: "Page Counters", content: "" },
      { name: "Components", content: "" },
      { name: "Volumes", content: "" },
      { name: "Connections", content: "" },
      { name: "Network Ports", content: "" },
      { name: "Sockets", content: "" },
      { name: "Management", content: "" },
      { name: "Contracts", content: "" },
      { name: "Documents", content: "" },
      { name: "Knowledge Base", content: "" },
      { name: "Tickets", content: "" },
      { name: "Problems", content: "" },
      { name: "Changes", content: "" },
      { name: "Links", content: "" },
      { name: "Notes", content: "" },
      { name: "Reservations", content: "" },
      { name: "Certificates", content: "" },
      { name: "Domains", content: "" },
      { name: "Appliances", content: "" },
      { name: "Historical", content: "" },
      { name: "All", content: "" },
    ],
  },
  {
    name: "Cartridges",
    useGetAssetData: useGetComputerById,
    options: [
      { name: "Cartridge Models", content: <CartridgeForm isEditing={true} /> },
      { name: "Cartridges", content: "" },
      { name: "Printer Models", content: "" },
      { name: "Management", content: "" },
      { name: "Documents", content: "" },
      { name: "Links", content: "" },
      { name: "Notes", content: "" },
      { name: "Historical", content: "" },
      { name: "All", content: "" },
    ],
  },
  {
    name: "Consumables",
    useGetAssetData: useGetComputerById,
    options: [
      {
        name: "Consumable Models",
        content: <ConsumableForm isEditing={true} />,
      },
      { name: "Consumables", content: "" },
      { name: "Management", content: "" },
      { name: "Documents", content: "" },
      { name: "Links", content: "" },
      { name: "Notes", content: "" },
      { name: "Historical", content: "" },
      { name: "All", content: "" },
    ],
  },
  {
    name: "Phones",
    useGetAssetData: useGetComputerById,
    options: [
      { name: "Phones", content: <PhoneForm isEditing={true} /> },
      { name: "Impact Analysis", content: "" },
      { name: "Operating Systems", content: "" },
      { name: "Software", content: "" },
      { name: "Components", content: "" },
      { name: "Volumes", content: "" },
      { name: "Connections", content: "" },
      { name: "Network Ports", content: "" },
      { name: "Sockets", content: "" },
      { name: "Remote Management", content: "" },
      { name: "Management", content: "" },
      { name: "Contracts", content: "" },
      { name: "Documents", content: "" },
      { name: "Knowledge Base", content: "" },
      { name: "Tickets", content: "" },
      { name: "Problems", content: "" },
      { name: "Changes", content: "" },
      { name: "Links", content: "" },
      { name: "Notes", content: "" },
      { name: "Reservations", content: "" },
      { name: "Domains", content: "" },
      { name: "Appliances", content: "" },
      { name: "Historical", content: "" },
      { name: "All", content: "" },
    ],
  },
  {
    name: "Racks",
    useGetAssetData: useGetComputerById,
    options: [
      { name: "Items", content: "" },
      { name: "Racks", content: <RackForm isEditing={true} /> },
      { name: "Impact Analysis", content: "" },
      { name: "Management", content: "" },
      { name: "Contracts", content: "" },
      { name: "Documents", content: "" },
      { name: "Tickets", content: "" },
      { name: "Problems", content: "" },
      { name: "Changes", content: "" },
      { name: "Historical", content: "" },
      { name: "All", content: "" },
    ],
  },
  {
    name: "Enclosures",
    useGetAssetData: useGetComputerById,
    options: [
      { name: "Enclosures", content: <EnclosuresForm isEditing={true} /> },
      { name: "Impact Analysis", content: "" },
      { name: "Items", content: "" },
      { name: "Components", content: "" },
      { name: "Network Ports", content: "" },
      { name: "Management", content: "" },
      { name: "Contracts", content: "" },
      { name: "Documents", content: "" },
      { name: "Tickets", content: "" },
      { name: "Problems", content: "" },
      { name: "Changes", content: "" },
      { name: "Historical", content: "" },
      { name: "All", content: "" },
    ],
  },
  {
    name: "Pdu",
    useGetAssetData: useGetComputerById,
    options: [
      { name: "PDUs", content: <PduForm isEditing={true} /> },
      { name: "Impact Analysis", content: "" },
      { name: "PDU plugs", content: "" },
      { name: "Network Ports", content: "" },
      { name: "Management", content: "" },
      { name: "Contracts", content: "" },
      { name: "Documents", content: "" },
      { name: "Tickets", content: "" },
      { name: "Problems", content: "" },
      { name: "Changes", content: "" },
      { name: "Historical", content: "" },
      { name: "All", content: "" },
    ],
  },
  {
    name: "Passivedevices",
    useGetAssetData: useGetComputerById,
    options: [
      {
        name: "Passive Devices",
        content: <PassiveDeviceForm isEditing={true} />,
      },
      { name: "Sockets", content: "" },
      { name: "Management", content: "" },
      { name: "Contracts", content: "" },
      { name: "Documents", content: "" },
      { name: "Tickets", content: "" },
      { name: "Problems", content: "" },
      { name: "Changes", content: "" },
      { name: "Historical", content: "" },
      { name: "All", content: "" },
    ],
  },
  {
    name: "Unmanaged Devices",
    useGetAssetData: useGetComputerById,
    options: [],
  },
  {
    name: "Cables",
    useGetAssetData: useGetComputerById,
    options: [
      { name: "Cable", content: <CableForm isEditing={true} /> },
      { name: "Management", content: "" },
      { name: "Tickets", content: "" },
      { name: "Problems", content: "" },
      { name: "Changes", content: "" },
      { name: "Historical", content: "" },
      { name: "All", content: "" },
    ],
  },
  {
    name: "Simcards",
    useGetAssetData: useGetComputerById,
    options: [
      { name: "Simcards", content: <SimCardForm isEditing={true} /> },
      { name: "Management", content: "" },
      { name: "Documents", content: "" },
      { name: "Historical", content: "" },
      { name: "All", content: "" },
    ],
  },
];
