import CableForm from "../../components/forms/CableForm";
import CartridgeForm from "../../components/forms/CartridgeForm";
import ComputerForm from "../../components/forms/ComputerForm";
import ConsumableForm from "../../components/forms/ConsumableForm";
import DeviceForm from "../../components/forms/DeviceForm";
import EnclosuresForm from "../../components/forms/EnclosuresForm";
import MonitorForm from "../../components/forms/MonitorForm";
import NetDeviceForm from "../../components/forms/NetworkDeviceForm";
import PassiveDeviceForm from "../../components/forms/PassiveDeviceForm";
import PduForm from "../../components/forms/PduForm";
import PhoneForm from "../../components/forms/PhoneForm";
import PrinterForm from "../../components/forms/PrinterForm";
import RackForm from "../../components/forms/RackForm";
import SimCardForm from "../../components/forms/SimCardForm";
import SoftwareForm from "../../components/forms/SoftwareForm";

export interface EditAssetOption {
  name: string;
  options: { name: string; content: any }[];
}

export const AssetOptions: EditAssetOption[] = [
  {
    name: "Computers",
    options: [
      { name: "Computers", content: <ComputerForm /> },
      { name: "Impact Analysis", content: "" },
      { name: "Operating Systems", content: "" },
      { name: "Components", content: "" },
      { name: "Volumes", content: "" },
      { name: "Software", content: "" },
      { name: "Conections", content: "" },
      { name: "Network Ports", content: "" },
      { name: "Sockets", content: "" },
      { name: "Remote Management", content: "" },
      { name: "Management", content: "" },
      { name: "Contracts", content: "" },
      { name: "Documents", content: "" },
      { name: "Virtualization", content: "" },
      { name: "Antiviruses", content: "" },
      { name: "Knowledge Base", content: "" },
      { name: "Tickets", content: "" },
      { name: "Problems", content: "" },
      { name: "Changes", content: "" },
      { name: "Links", content: "" },
      { name: "Certificates", content: "" },
      { name: "Notes", content: "" },
      { name: "Reservations", content: "" },
      { name: "Domains", content: "" },
      { name: "Appliances", content: "" },
      { name: "Database Instances", content: "" },
      { name: "Historical", content: "" },
      { name: "All", content: "" },
    ],
  },
  {
    name: "Monitors",
    options: [
      { name: "Monitors", content: <MonitorForm /> },
      { name: "Impact Analysis", content: "" },
      { name: "Operating Systems", content: "" },
      { name: "Software", content: "" },
      { name: "Connections", content: "" },
      { name: "Network Ports", content: "" },
      { name: "Management", content: "" },
      { name: "Contracts", content: "" },
      { name: "Documents", content: "" },
      { name: "Knowledge Base", content: "" },
      { name: "Tickets", content: "" },
      { name: "Problems", content: "" },
      { name: "Changes", content: "" },
      { name: "Links", content: "" },
      { name: "Notes", content: "" },
      { name: "Reservations", content: "" },
      { name: "Domains", content: "" },
      { name: "Appliances", content: "" },
      { name: "Historical", content: "" },
      { name: "All", content: "" },
    ],
  },
  {
    name: "Software",
    options: [
      { name: "Software", content: <SoftwareForm /> },
      { name: "Impact Analysis", content: "" },
      { name: "Versions", content: "" },
      { name: "Licenses", content: "" },
      { name: "Installations", content: "" },
      { name: "Management", content: "" },
      { name: "Contracts", content: "" },
      { name: "Documents", content: "" },
      { name: "Knowledge Base", content: "" },
      { name: "Tickets", content: "" },
      { name: "Problems", content: "" },
      { name: "Changes", content: "" },
      { name: "Links", content: "" },
      { name: "Notes", content: "" },
      { name: "Reservations", content: "" },
      { name: "Domains", content: "" },
      { name: "Appliances", content: "" },
      { name: "Historical", content: "" },
      { name: "All", content: "" },
    ],
  },
  {
    name: "Networkequipments",
    options: [
      { name: "Network Devices", content: <NetDeviceForm /> },
      { name: "Impact Analysis", content: "" },
      { name: "Operating Systems", content: "" },
      { name: "Software", content: "" },
      { name: "Components", content: "" },
      { name: "Volumes", content: "" },
      { name: "Network Ports", content: "" },
      { name: "Network Names", content: "" },
      { name: "Sockets", content: "" },
      { name: "Management", content: "" },
      { name: "Contracts", content: "" },
      { name: "Documents", content: "" },
      { name: "Knowledge Base", content: "" },
      { name: "Tickets", content: "" },
      { name: "Problems", content: "" },
      { name: "Changes", content: "" },
      { name: "Links", content: "" },
      { name: "Notes", content: "" },
      { name: "Reservations", content: "" },
      { name: "Certificates", content: "" },
      { name: "Domains", content: "" },
      { name: "Appliances", content: "" },
      { name: "Historical", content: "" },
      { name: "All", content: "" },
    ],
  },
  {
    name: "Devices",
    options: [
      { name: "Devices", content: <DeviceForm /> },
      { name: "Impact Analysis", content: "" },
      { name: "Operating Systems", content: "" },
      { name: "Software", content: "" },
      { name: "Components", content: "" },
      { name: "Connections", content: "" },
      { name: "Network Ports", content: "" },
      { name: "Sockets", content: "" },
      { name: "Management", content: "" },
      { name: "Contracts", content: "" },
      { name: "Documents", content: "" },
      { name: "Knowledge Base", content: "" },
      { name: "Tickets", content: "" },
      { name: "Problems", content: "" },
      { name: "Changes", content: "" },
      { name: "Links", content: "" },
      { name: "Notes", content: "" },
      { name: "Reservations", content: "" },
      { name: "Certificates", content: "" },
      { name: "Domains", content: "" },
      { name: "Appliances", content: "" },
      { name: "Historical", content: "" },
      { name: "All", content: "" },
    ],
  },
  {
    name: "Printers",
    options: [
      { name: "Printers", content: <PrinterForm /> },
      { name: "Impact Analysis", content: "" },
      { name: "Operating Systems", content: "" },
      { name: "Software", content: "" },
      { name: "Cartridges", content: "" },
      { name: "Page Counters", content: "" },
      { name: "Components", content: "" },
      { name: "Volumes", content: "" },
      { name: "Connections", content: "" },
      { name: "Network Ports", content: "" },
      { name: "Sockets", content: "" },
      { name: "Management", content: "" },
      { name: "Contracts", content: "" },
      { name: "Documents", content: "" },
      { name: "Knowledge Base", content: "" },
      { name: "Tickets", content: "" },
      { name: "Problems", content: "" },
      { name: "Changes", content: "" },
      { name: "Links", content: "" },
      { name: "Notes", content: "" },
      { name: "Reservations", content: "" },
      { name: "Certificates", content: "" },
      { name: "Domains", content: "" },
      { name: "Appliances", content: "" },
      { name: "Historical", content: "" },
      { name: "All", content: "" },
    ],
  },
  {
    name: "Cartridges",
    options: [
      { name: "Cartridge Models", content: <CartridgeForm /> },
      { name: "Cartridges", content: "" },
      { name: "Printer Models", content: "" },
      { name: "Management", content: "" },
      { name: "Documents", content: "" },
      { name: "Links", content: "" },
      { name: "Notes", content: "" },
      { name: "Historical", content: "" },
      { name: "All", content: "" },
    ],
  },
  {
    name: "Consumables",
    options: [
      { name: "Consumable Models", content: <ConsumableForm /> },
      { name: "Consumables", content: "" },
      { name: "Management", content: "" },
      { name: "Documents", content: "" },
      { name: "Links", content: "" },
      { name: "Notes", content: "" },
      { name: "Historical", content: "" },
      { name: "All", content: "" },
    ],
  },
  {
    name: "Phones",
    options: [
      { name: "Phones", content: <PhoneForm /> },
      { name: "Impact Analysis", content: "" },
      { name: "Operating Systems", content: "" },
      { name: "Software", content: "" },
      { name: "Components", content: "" },
      { name: "Volumes", content: "" },
      { name: "Connections", content: "" },
      { name: "Network Ports", content: "" },
      { name: "Sockets", content: "" },
      { name: "Remote Management", content: "" },
      { name: "Management", content: "" },
      { name: "Contracts", content: "" },
      { name: "Documents", content: "" },
      { name: "Knowledge Base", content: "" },
      { name: "Tickets", content: "" },
      { name: "Problems", content: "" },
      { name: "Changes", content: "" },
      { name: "Links", content: "" },
      { name: "Notes", content: "" },
      { name: "Reservations", content: "" },
      { name: "Domains", content: "" },
      { name: "Appliances", content: "" },
      { name: "Historical", content: "" },
      { name: "All", content: "" },
    ],
  },
  {
    name: "Racks",
    options: [
      { name: "Items", content: "" },
      { name: "Racks", content: <RackForm /> },
      { name: "Impact Analysis", content: "" },
      { name: "Management", content: "" },
      { name: "Contracts", content: "" },
      { name: "Documents", content: "" },
      { name: "Tickets", content: "" },
      { name: "Problems", content: "" },
      { name: "Changes", content: "" },
      { name: "Historical", content: "" },
      { name: "All", content: "" },
    ],
  },
  {
    name: "Enclosures",
    options: [
      { name: "Enclosures", content: <EnclosuresForm /> },
      { name: "Impact Analysis", content: "" },
      { name: "Items", content: "" },
      { name: "Components", content: "" },
      { name: "Network Ports", content: "" },
      { name: "Management", content: "" },
      { name: "Contracts", content: "" },
      { name: "Documents", content: "" },
      { name: "Tickets", content: "" },
      { name: "Problems", content: "" },
      { name: "Changes", content: "" },
      { name: "Historical", content: "" },
      { name: "All", content: "" },
    ],
  },
  {
    name: "Pdu",
    options: [
      { name: "PDUs", content: <PduForm /> },
      { name: "Impact Analysis", content: "" },
      { name: "PDU plugs", content: "" },
      { name: "Network Ports", content: "" },
      { name: "Management", content: "" },
      { name: "Contracts", content: "" },
      { name: "Documents", content: "" },
      { name: "Tickets", content: "" },
      { name: "Problems", content: "" },
      { name: "Changes", content: "" },
      { name: "Historical", content: "" },
      { name: "All", content: "" },
    ],
  },
  {
    name: "Passivedevices",
    options: [
      { name: "Passive Devices", content: <PassiveDeviceForm /> },
      { name: "Sockets", content: "" },
      { name: "Management", content: "" },
      { name: "Contracts", content: "" },
      { name: "Documents", content: "" },
      { name: "Tickets", content: "" },
      { name: "Problems", content: "" },
      { name: "Changes", content: "" },
      { name: "Historical", content: "" },
      { name: "All", content: "" },
    ],
  },
  {
    name: "Unmanaged Devices",
    options: [],
  },
  {
    name: "Cables",
    options: [
      { name: "Cable", content: <CableForm /> },
      { name: "Management", content: "" },
      { name: "Tickets", content: "" },
      { name: "Problems", content: "" },
      { name: "Changes", content: "" },
      { name: "Historical", content: "" },
      { name: "All", content: "" },
    ],
  },
  {
    name: "Simcards",
    options: [
      { name: "Simcards", content: <SimCardForm /> },
      { name: "Management", content: "" },
      { name: "Documents", content: "" },
      { name: "Historical", content: "" },
      { name: "All", content: "" },
    ],
  },
];
