export interface Entities {
  id?: number
  name?: string
  completename?: string
  comment?: string
  level?: number
  sons_cache?: string
  ancestors_cache?: string
  registration_number?: string
  address?: string
  postcode?: string
  town?: string
  state?: string
  country?: string
  website?: string
  phonenumber?: string
  fax?: string
  email?: string
  admin_email?: string
  admin_email_name?: string
  from_email?: string
  from_email_name?: string
  noreply_email?: string
  noreply_email_name?: string
  replyto_email?: string
  replyto_email_name?: string
  notification_subject_tag?: string
  ldap_dn?: string
  tag?: string
  mail_domain?: string
  entity_ldapfilter?: string
  mailing_signature?: string
  cartridges_alert_repeat?: number
  consumables_alert_repeat?: number
  use_licenses_alert?: number
  send_licenses_alert_before_delay?: number
  use_certificates_alert?: number
  send_certificates_alert_before_delay?: number
  certificates_alert_repeat_interval?: number
  use_contracts_alert?: number
  send_contracts_alert_before_delay?: number
  use_infocoms_alert?: number
  send_infocoms_alert_before_delay?: number
  use_reservations_alert?: number
  use_domains_alert?: number
  send_domains_alert_close_expiries_delay?: number
  send_domains_alert_expired_delay?: number
  autoclose_delay?: number
  autopurge_delay?: number
  notclosed_delay?: number
  calendars_strategy?: number
  auto_assign_mode?: number
  tickettype?: number
  max_closedate?: string
  inquest_config?: number
  inquest_rate?: number
  inquest_delay?: number
  inquest_url?: string
  autofill_warranty_date?: string
  autofill_use_date?: string
  autofill_buy_date?: string
  autofill_delivery_date?: string
  autofill_order_date?: string
  tickettemplates_strategy?: number
  changetemplates_strategy?: number
  changetemplates?: number
  problemtemplates_strategy?: number
  problemtemplates?: number
  entities_strategy_software?: number
  entities_software?: number
  default_contract_alert?: number
  default_infocom_alert?: number
  default_cartridges_alarm_threshold?: number
  default_consumables_alarm_threshold?: number
  delay_send_emails?: number
  is_notif_enable_default?: number
  inquest_duration?: number
  date_mod?: string
  date_creation?: string
  autofill_decommission_date?: string
  suppliers_as_private?: number
  anonymize_support_agents?: number
  display_users_initials?: number
  contracts_strategy_default?: number
  contracts_default?: number
  enable_custom_css?: number
  custom_css_code?: string
  latitude?: string
  longitude?: string
  altitude?: string
  transfers_strategy?: number
  transfers?: number
  agent_base_url?: string
  entities?: string
  authldaps?: number
  calendars?: number
  tickettemplates?: number
}






